package com.unisk.zc.entitys;

import java.util.Date;

public class AgreeAndAgainstLog extends BaseQuery<AgreeAndAgainstLog> {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_d_agree_and_against_log.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_d_agree_and_against_log.PROJECTID
     *
     * @mbggenerated
     */
    private Integer projectid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_d_agree_and_against_log.USERID
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_d_agree_and_against_log.OPRERATION
     *
     * @mbggenerated
     */
    private Integer opreration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_d_agree_and_against_log.DELMARK
     *
     * @mbggenerated
     */
    private Integer delmark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_d_agree_and_against_log.CREATETIME
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_d_agree_and_against_log.CREATEUSERID
     *
     * @mbggenerated
     */
    private Integer createuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_d_agree_and_against_log.MODIFYTIME
     *
     * @mbggenerated
     */
    private Date modifytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_d_agree_and_against_log.MODIFYUSERID
     *
     * @mbggenerated
     */
    private Integer modifyuserid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_d_agree_and_against_log.ID
     *
     * @return the value of tb_d_agree_and_against_log.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_d_agree_and_against_log.ID
     *
     * @param id the value for tb_d_agree_and_against_log.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_d_agree_and_against_log.PROJECTID
     *
     * @return the value of tb_d_agree_and_against_log.PROJECTID
     *
     * @mbggenerated
     */
    public Integer getProjectid() {
        return projectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_d_agree_and_against_log.PROJECTID
     *
     * @param projectid the value for tb_d_agree_and_against_log.PROJECTID
     *
     * @mbggenerated
     */
    public void setProjectid(Integer projectid) {
        this.projectid = projectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_d_agree_and_against_log.USERID
     *
     * @return the value of tb_d_agree_and_against_log.USERID
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_d_agree_and_against_log.USERID
     *
     * @param userid the value for tb_d_agree_and_against_log.USERID
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_d_agree_and_against_log.OPRERATION
     *
     * @return the value of tb_d_agree_and_against_log.OPRERATION
     *
     * @mbggenerated
     */
    public Integer getOpreration() {
        return opreration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_d_agree_and_against_log.OPRERATION
     *
     * @param opreration the value for tb_d_agree_and_against_log.OPRERATION
     *
     * @mbggenerated
     */
    public void setOpreration(Integer opreration) {
        this.opreration = opreration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_d_agree_and_against_log.DELMARK
     *
     * @return the value of tb_d_agree_and_against_log.DELMARK
     *
     * @mbggenerated
     */
    public Integer getDelmark() {
        return delmark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_d_agree_and_against_log.DELMARK
     *
     * @param delmark the value for tb_d_agree_and_against_log.DELMARK
     *
     * @mbggenerated
     */
    public void setDelmark(Integer delmark) {
        this.delmark = delmark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_d_agree_and_against_log.CREATETIME
     *
     * @return the value of tb_d_agree_and_against_log.CREATETIME
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_d_agree_and_against_log.CREATETIME
     *
     * @param createtime the value for tb_d_agree_and_against_log.CREATETIME
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_d_agree_and_against_log.CREATEUSERID
     *
     * @return the value of tb_d_agree_and_against_log.CREATEUSERID
     *
     * @mbggenerated
     */
    public Integer getCreateuserid() {
        return createuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_d_agree_and_against_log.CREATEUSERID
     *
     * @param createuserid the value for tb_d_agree_and_against_log.CREATEUSERID
     *
     * @mbggenerated
     */
    public void setCreateuserid(Integer createuserid) {
        this.createuserid = createuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_d_agree_and_against_log.MODIFYTIME
     *
     * @return the value of tb_d_agree_and_against_log.MODIFYTIME
     *
     * @mbggenerated
     */
    public Date getModifytime() {
        return modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_d_agree_and_against_log.MODIFYTIME
     *
     * @param modifytime the value for tb_d_agree_and_against_log.MODIFYTIME
     *
     * @mbggenerated
     */
    public void setModifytime(Date modifytime) {
        this.modifytime = modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_d_agree_and_against_log.MODIFYUSERID
     *
     * @return the value of tb_d_agree_and_against_log.MODIFYUSERID
     *
     * @mbggenerated
     */
    public Integer getModifyuserid() {
        return modifyuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_d_agree_and_against_log.MODIFYUSERID
     *
     * @param modifyuserid the value for tb_d_agree_and_against_log.MODIFYUSERID
     *
     * @mbggenerated
     */
    public void setModifyuserid(Integer modifyuserid) {
        this.modifyuserid = modifyuserid;
    }
}