package com.unisk.zc.entitys;

import java.util.Date;

public class Department extends BaseQuery<Department> {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_D_DEPARTMENT.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_D_DEPARTMENT.DEPTNAME
     *
     * @mbggenerated
     */
    private String deptname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_D_DEPARTMENT.DEPTNO
     *
     * @mbggenerated
     */
    private String deptno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_D_DEPARTMENT.PARENTID
     *
     * @mbggenerated
     */
    private Integer parentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_D_DEPARTMENT.SORTCODE
     *
     * @mbggenerated
     */
    private Integer sortcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_D_DEPARTMENT.REMARKS
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_D_DEPARTMENT.DELMARK
     *
     * @mbggenerated
     */
    private Integer delmark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_D_DEPARTMENT.CREATETIME
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_D_DEPARTMENT.CREATEUSERID
     *
     * @mbggenerated
     */
    private Integer createuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_D_DEPARTMENT.MODIFYTIME
     *
     * @mbggenerated
     */
    private Date modifytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_D_DEPARTMENT.MODIFYUSERID
     *
     * @mbggenerated
     */
    private Integer modifyuserid;
    
    private Integer wechatstatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_D_DEPARTMENT.ID
     *
     * @return the value of TB_D_DEPARTMENT.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_D_DEPARTMENT.ID
     *
     * @param id the value for TB_D_DEPARTMENT.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_D_DEPARTMENT.DEPTNAME
     *
     * @return the value of TB_D_DEPARTMENT.DEPTNAME
     *
     * @mbggenerated
     */
    public String getDeptname() {
        return deptname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_D_DEPARTMENT.DEPTNAME
     *
     * @param deptname the value for TB_D_DEPARTMENT.DEPTNAME
     *
     * @mbggenerated
     */
    public void setDeptname(String deptname) {
        this.deptname = deptname == null ? null : deptname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_D_DEPARTMENT.DEPTNO
     *
     * @return the value of TB_D_DEPARTMENT.DEPTNO
     *
     * @mbggenerated
     */
    public String getDeptno() {
        return deptno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_D_DEPARTMENT.DEPTNO
     *
     * @param deptno the value for TB_D_DEPARTMENT.DEPTNO
     *
     * @mbggenerated
     */
    public void setDeptno(String deptno) {
        this.deptno = deptno == null ? null : deptno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_D_DEPARTMENT.PARENTID
     *
     * @return the value of TB_D_DEPARTMENT.PARENTID
     *
     * @mbggenerated
     */
    public Integer getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_D_DEPARTMENT.PARENTID
     *
     * @param parentid the value for TB_D_DEPARTMENT.PARENTID
     *
     * @mbggenerated
     */
    public void setParentid(Integer parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_D_DEPARTMENT.SORTCODE
     *
     * @return the value of TB_D_DEPARTMENT.SORTCODE
     *
     * @mbggenerated
     */
    public Integer getSortcode() {
        return sortcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_D_DEPARTMENT.SORTCODE
     *
     * @param sortcode the value for TB_D_DEPARTMENT.SORTCODE
     *
     * @mbggenerated
     */
    public void setSortcode(Integer sortcode) {
        this.sortcode = sortcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_D_DEPARTMENT.REMARKS
     *
     * @return the value of TB_D_DEPARTMENT.REMARKS
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_D_DEPARTMENT.REMARKS
     *
     * @param remarks the value for TB_D_DEPARTMENT.REMARKS
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_D_DEPARTMENT.DELMARK
     *
     * @return the value of TB_D_DEPARTMENT.DELMARK
     *
     * @mbggenerated
     */
    public Integer getDelmark() {
        return delmark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_D_DEPARTMENT.DELMARK
     *
     * @param delmark the value for TB_D_DEPARTMENT.DELMARK
     *
     * @mbggenerated
     */
    public void setDelmark(Integer delmark) {
        this.delmark = delmark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_D_DEPARTMENT.CREATETIME
     *
     * @return the value of TB_D_DEPARTMENT.CREATETIME
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_D_DEPARTMENT.CREATETIME
     *
     * @param createtime the value for TB_D_DEPARTMENT.CREATETIME
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_D_DEPARTMENT.CREATEUSERID
     *
     * @return the value of TB_D_DEPARTMENT.CREATEUSERID
     *
     * @mbggenerated
     */
    public Integer getCreateuserid() {
        return createuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_D_DEPARTMENT.CREATEUSERID
     *
     * @param createuserid the value for TB_D_DEPARTMENT.CREATEUSERID
     *
     * @mbggenerated
     */
    public void setCreateuserid(Integer createuserid) {
        this.createuserid = createuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_D_DEPARTMENT.MODIFYTIME
     *
     * @return the value of TB_D_DEPARTMENT.MODIFYTIME
     *
     * @mbggenerated
     */
    public Date getModifytime() {
        return modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_D_DEPARTMENT.MODIFYTIME
     *
     * @param modifytime the value for TB_D_DEPARTMENT.MODIFYTIME
     *
     * @mbggenerated
     */
    public void setModifytime(Date modifytime) {
        this.modifytime = modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_D_DEPARTMENT.MODIFYUSERID
     *
     * @return the value of TB_D_DEPARTMENT.MODIFYUSERID
     *
     * @mbggenerated
     */
    public Integer getModifyuserid() {
        return modifyuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_D_DEPARTMENT.MODIFYUSERID
     *
     * @param modifyuserid the value for TB_D_DEPARTMENT.MODIFYUSERID
     *
     * @mbggenerated
     */
    public void setModifyuserid(Integer modifyuserid) {
        this.modifyuserid = modifyuserid;
    }

	public Integer getWechatstatus() {
		return wechatstatus;
	}

	public void setWechatstatus(Integer wechatstatus) {
		this.wechatstatus = wechatstatus;
	}
}