package com.unisk.zc.entitys;

import java.util.Date;

public class Menu extends BaseQuery<Menu> {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_D_MENU.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_D_MENU.MENUNAME
     *
     * @mbggenerated
     */
    private String menuname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_D_MENU.MENUICON
     *
     * @mbggenerated
     */
    private String menuicon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_D_MENU.PARENTID
     *
     * @mbggenerated
     */
    private Integer parentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_D_MENU.TARGET
     *
     * @mbggenerated
     */
    private String target;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_D_MENU.MENUHREF
     *
     * @mbggenerated
     */
    private String menuhref;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_D_MENU.ISSHOW
     *
     * @mbggenerated
     */
    private Integer isshow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_D_MENU.SORTCODE
     *
     * @mbggenerated
     */
    private Integer sortcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_D_MENU.ALLOWDEL
     *
     * @mbggenerated
     */
    private Integer allowdel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_D_MENU.ALLOWEDIT
     *
     * @mbggenerated
     */
    private Integer allowedit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_D_MENU.REMARKS
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_D_MENU.DELMARK
     *
     * @mbggenerated
     */
    private Integer delmark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_D_MENU.CREATETIME
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_D_MENU.CREATEUSERID
     *
     * @mbggenerated
     */
    private Integer createuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_D_MENU.MODIFYTIME
     *
     * @mbggenerated
     */
    private Date modifytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_D_MENU.MODIFYUSERID
     *
     * @mbggenerated
     */
    private Integer modifyuserid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_D_MENU.ID
     *
     * @return the value of TB_D_MENU.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_D_MENU.ID
     *
     * @param id the value for TB_D_MENU.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_D_MENU.MENUNAME
     *
     * @return the value of TB_D_MENU.MENUNAME
     *
     * @mbggenerated
     */
    public String getMenuname() {
        return menuname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_D_MENU.MENUNAME
     *
     * @param menuname the value for TB_D_MENU.MENUNAME
     *
     * @mbggenerated
     */
    public void setMenuname(String menuname) {
        this.menuname = menuname == null ? null : menuname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_D_MENU.MENUICON
     *
     * @return the value of TB_D_MENU.MENUICON
     *
     * @mbggenerated
     */
    public String getMenuicon() {
        return menuicon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_D_MENU.MENUICON
     *
     * @param menuicon the value for TB_D_MENU.MENUICON
     *
     * @mbggenerated
     */
    public void setMenuicon(String menuicon) {
        this.menuicon = menuicon == null ? null : menuicon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_D_MENU.PARENTID
     *
     * @return the value of TB_D_MENU.PARENTID
     *
     * @mbggenerated
     */
    public Integer getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_D_MENU.PARENTID
     *
     * @param parentid the value for TB_D_MENU.PARENTID
     *
     * @mbggenerated
     */
    public void setParentid(Integer parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_D_MENU.TARGET
     *
     * @return the value of TB_D_MENU.TARGET
     *
     * @mbggenerated
     */
    public String getTarget() {
        return target;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_D_MENU.TARGET
     *
     * @param target the value for TB_D_MENU.TARGET
     *
     * @mbggenerated
     */
    public void setTarget(String target) {
        this.target = target == null ? null : target.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_D_MENU.MENUHREF
     *
     * @return the value of TB_D_MENU.MENUHREF
     *
     * @mbggenerated
     */
    public String getMenuhref() {
        return menuhref;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_D_MENU.MENUHREF
     *
     * @param menuhref the value for TB_D_MENU.MENUHREF
     *
     * @mbggenerated
     */
    public void setMenuhref(String menuhref) {
        this.menuhref = menuhref == null ? null : menuhref.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_D_MENU.ISSHOW
     *
     * @return the value of TB_D_MENU.ISSHOW
     *
     * @mbggenerated
     */
    public Integer getIsshow() {
        return isshow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_D_MENU.ISSHOW
     *
     * @param isshow the value for TB_D_MENU.ISSHOW
     *
     * @mbggenerated
     */
    public void setIsshow(Integer isshow) {
        this.isshow = isshow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_D_MENU.SORTCODE
     *
     * @return the value of TB_D_MENU.SORTCODE
     *
     * @mbggenerated
     */
    public Integer getSortcode() {
        return sortcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_D_MENU.SORTCODE
     *
     * @param sortcode the value for TB_D_MENU.SORTCODE
     *
     * @mbggenerated
     */
    public void setSortcode(Integer sortcode) {
        this.sortcode = sortcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_D_MENU.ALLOWDEL
     *
     * @return the value of TB_D_MENU.ALLOWDEL
     *
     * @mbggenerated
     */
    public Integer getAllowdel() {
        return allowdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_D_MENU.ALLOWDEL
     *
     * @param allowdel the value for TB_D_MENU.ALLOWDEL
     *
     * @mbggenerated
     */
    public void setAllowdel(Integer allowdel) {
        this.allowdel = allowdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_D_MENU.ALLOWEDIT
     *
     * @return the value of TB_D_MENU.ALLOWEDIT
     *
     * @mbggenerated
     */
    public Integer getAllowedit() {
        return allowedit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_D_MENU.ALLOWEDIT
     *
     * @param allowedit the value for TB_D_MENU.ALLOWEDIT
     *
     * @mbggenerated
     */
    public void setAllowedit(Integer allowedit) {
        this.allowedit = allowedit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_D_MENU.REMARKS
     *
     * @return the value of TB_D_MENU.REMARKS
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_D_MENU.REMARKS
     *
     * @param remarks the value for TB_D_MENU.REMARKS
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_D_MENU.DELMARK
     *
     * @return the value of TB_D_MENU.DELMARK
     *
     * @mbggenerated
     */
    public Integer getDelmark() {
        return delmark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_D_MENU.DELMARK
     *
     * @param delmark the value for TB_D_MENU.DELMARK
     *
     * @mbggenerated
     */
    public void setDelmark(Integer delmark) {
        this.delmark = delmark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_D_MENU.CREATETIME
     *
     * @return the value of TB_D_MENU.CREATETIME
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_D_MENU.CREATETIME
     *
     * @param createtime the value for TB_D_MENU.CREATETIME
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_D_MENU.CREATEUSERID
     *
     * @return the value of TB_D_MENU.CREATEUSERID
     *
     * @mbggenerated
     */
    public Integer getCreateuserid() {
        return createuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_D_MENU.CREATEUSERID
     *
     * @param createuserid the value for TB_D_MENU.CREATEUSERID
     *
     * @mbggenerated
     */
    public void setCreateuserid(Integer createuserid) {
        this.createuserid = createuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_D_MENU.MODIFYTIME
     *
     * @return the value of TB_D_MENU.MODIFYTIME
     *
     * @mbggenerated
     */
    public Date getModifytime() {
        return modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_D_MENU.MODIFYTIME
     *
     * @param modifytime the value for TB_D_MENU.MODIFYTIME
     *
     * @mbggenerated
     */
    public void setModifytime(Date modifytime) {
        this.modifytime = modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_D_MENU.MODIFYUSERID
     *
     * @return the value of TB_D_MENU.MODIFYUSERID
     *
     * @mbggenerated
     */
    public Integer getModifyuserid() {
        return modifyuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_D_MENU.MODIFYUSERID
     *
     * @param modifyuserid the value for TB_D_MENU.MODIFYUSERID
     *
     * @mbggenerated
     */
    public void setModifyuserid(Integer modifyuserid) {
        this.modifyuserid = modifyuserid;
    }
}