package com.unisk.zc.entitys;

import java.util.Date;

public class Partner extends BaseQuery<Partner>{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_d_partner.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_d_partner.PARTNERNAME
     *
     * @mbggenerated
     */
    private String partnername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_d_partner.INDUSTRY
     *
     * @mbggenerated
     */
    private String industry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_d_partner.PARTNERADDR
     *
     * @mbggenerated
     */
    private String partneraddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_d_partner.PARTNERWEB
     *
     * @mbggenerated
     */
    private String partnerweb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_d_partner.PARTNERLOGO
     *
     * @mbggenerated
     */
    private String partnerlogo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_d_partner.PARTNEREXPERIENCE
     *
     * @mbggenerated
     */
    private String partnerexperience;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_d_partner.USERID
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_d_partner.REMARKS
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_d_partner.DELMARK
     *
     * @mbggenerated
     */
    private Integer delmark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_d_partner.CREATETIME
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_d_partner.CREATEUSERID
     *
     * @mbggenerated
     */
    private Integer createuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_d_partner.MODIFYTIME
     *
     * @mbggenerated
     */
    private Date modifytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_d_partner.MODIFYUSERID
     *
     * @mbggenerated
     */
    private Integer modifyuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_d_partner.PARTNERBRIEF
     *
     * @mbggenerated
     */
    private String partnerbrief;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_d_partner.ID
     *
     * @return the value of tb_d_partner.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_d_partner.ID
     *
     * @param id the value for tb_d_partner.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_d_partner.PARTNERNAME
     *
     * @return the value of tb_d_partner.PARTNERNAME
     *
     * @mbggenerated
     */
    public String getPartnername() {
        return partnername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_d_partner.PARTNERNAME
     *
     * @param partnername the value for tb_d_partner.PARTNERNAME
     *
     * @mbggenerated
     */
    public void setPartnername(String partnername) {
        this.partnername = partnername == null ? null : partnername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_d_partner.INDUSTRY
     *
     * @return the value of tb_d_partner.INDUSTRY
     *
     * @mbggenerated
     */
    public String getIndustry() {
        return industry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_d_partner.INDUSTRY
     *
     * @param industry the value for tb_d_partner.INDUSTRY
     *
     * @mbggenerated
     */
    public void setIndustry(String industry) {
        this.industry = industry == null ? null : industry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_d_partner.PARTNERADDR
     *
     * @return the value of tb_d_partner.PARTNERADDR
     *
     * @mbggenerated
     */
    public String getPartneraddr() {
        return partneraddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_d_partner.PARTNERADDR
     *
     * @param partneraddr the value for tb_d_partner.PARTNERADDR
     *
     * @mbggenerated
     */
    public void setPartneraddr(String partneraddr) {
        this.partneraddr = partneraddr == null ? null : partneraddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_d_partner.PARTNERWEB
     *
     * @return the value of tb_d_partner.PARTNERWEB
     *
     * @mbggenerated
     */
    public String getPartnerweb() {
        return partnerweb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_d_partner.PARTNERWEB
     *
     * @param partnerweb the value for tb_d_partner.PARTNERWEB
     *
     * @mbggenerated
     */
    public void setPartnerweb(String partnerweb) {
        this.partnerweb = partnerweb == null ? null : partnerweb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_d_partner.PARTNERLOGO
     *
     * @return the value of tb_d_partner.PARTNERLOGO
     *
     * @mbggenerated
     */
    public String getPartnerlogo() {
        return partnerlogo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_d_partner.PARTNERLOGO
     *
     * @param partnerlogo the value for tb_d_partner.PARTNERLOGO
     *
     * @mbggenerated
     */
    public void setPartnerlogo(String partnerlogo) {
        this.partnerlogo = partnerlogo == null ? null : partnerlogo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_d_partner.PARTNEREXPERIENCE
     *
     * @return the value of tb_d_partner.PARTNEREXPERIENCE
     *
     * @mbggenerated
     */
    public String getPartnerexperience() {
        return partnerexperience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_d_partner.PARTNEREXPERIENCE
     *
     * @param partnerexperience the value for tb_d_partner.PARTNEREXPERIENCE
     *
     * @mbggenerated
     */
    public void setPartnerexperience(String partnerexperience) {
        this.partnerexperience = partnerexperience == null ? null : partnerexperience.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_d_partner.USERID
     *
     * @return the value of tb_d_partner.USERID
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_d_partner.USERID
     *
     * @param userid the value for tb_d_partner.USERID
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_d_partner.REMARKS
     *
     * @return the value of tb_d_partner.REMARKS
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_d_partner.REMARKS
     *
     * @param remarks the value for tb_d_partner.REMARKS
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_d_partner.DELMARK
     *
     * @return the value of tb_d_partner.DELMARK
     *
     * @mbggenerated
     */
    public Integer getDelmark() {
        return delmark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_d_partner.DELMARK
     *
     * @param delmark the value for tb_d_partner.DELMARK
     *
     * @mbggenerated
     */
    public void setDelmark(Integer delmark) {
        this.delmark = delmark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_d_partner.CREATETIME
     *
     * @return the value of tb_d_partner.CREATETIME
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_d_partner.CREATETIME
     *
     * @param createtime the value for tb_d_partner.CREATETIME
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_d_partner.CREATEUSERID
     *
     * @return the value of tb_d_partner.CREATEUSERID
     *
     * @mbggenerated
     */
    public Integer getCreateuserid() {
        return createuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_d_partner.CREATEUSERID
     *
     * @param createuserid the value for tb_d_partner.CREATEUSERID
     *
     * @mbggenerated
     */
    public void setCreateuserid(Integer createuserid) {
        this.createuserid = createuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_d_partner.MODIFYTIME
     *
     * @return the value of tb_d_partner.MODIFYTIME
     *
     * @mbggenerated
     */
    public Date getModifytime() {
        return modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_d_partner.MODIFYTIME
     *
     * @param modifytime the value for tb_d_partner.MODIFYTIME
     *
     * @mbggenerated
     */
    public void setModifytime(Date modifytime) {
        this.modifytime = modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_d_partner.MODIFYUSERID
     *
     * @return the value of tb_d_partner.MODIFYUSERID
     *
     * @mbggenerated
     */
    public Integer getModifyuserid() {
        return modifyuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_d_partner.MODIFYUSERID
     *
     * @param modifyuserid the value for tb_d_partner.MODIFYUSERID
     *
     * @mbggenerated
     */
    public void setModifyuserid(Integer modifyuserid) {
        this.modifyuserid = modifyuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_d_partner.PARTNERBRIEF
     *
     * @return the value of tb_d_partner.PARTNERBRIEF
     *
     * @mbggenerated
     */
    public String getPartnerbrief() {
        return partnerbrief;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_d_partner.PARTNERBRIEF
     *
     * @param partnerbrief the value for tb_d_partner.PARTNERBRIEF
     *
     * @mbggenerated
     */
    public void setPartnerbrief(String partnerbrief) {
        this.partnerbrief = partnerbrief == null ? null : partnerbrief.trim();
    }
}