package com.unisk.zc.entitys;

import java.util.Date;

public class Partner2Project extends BaseQuery<Partner2Project>{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_r_partner2project.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_r_partner2project.PROJECTID
     *
     * @mbggenerated
     */
    private Integer projectid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_r_partner2project.PARTNERID
     *
     * @mbggenerated
     */
    private Integer partnerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_r_partner2project.STATUS
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_r_partner2project.CHECKTIME
     *
     * @mbggenerated
     */
    private Date checktime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_r_partner2project.CHECKUSERID
     *
     * @mbggenerated
     */
    private Integer checkuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_r_partner2project.REMARKS
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_r_partner2project.DELMARK
     *
     * @mbggenerated
     */
    private Integer delmark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_r_partner2project.CREATETIME
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_r_partner2project.CREATEUSERID
     *
     * @mbggenerated
     */
    private Integer createuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_r_partner2project.MODIFYTIME
     *
     * @mbggenerated
     */
    private Date modifytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_r_partner2project.MODIFYUSERID
     *
     * @mbggenerated
     */
    private Integer modifyuserid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_r_partner2project.ID
     *
     * @return the value of tb_r_partner2project.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_r_partner2project.ID
     *
     * @param id the value for tb_r_partner2project.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_r_partner2project.PROJECTID
     *
     * @return the value of tb_r_partner2project.PROJECTID
     *
     * @mbggenerated
     */
    public Integer getProjectid() {
        return projectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_r_partner2project.PROJECTID
     *
     * @param projectid the value for tb_r_partner2project.PROJECTID
     *
     * @mbggenerated
     */
    public void setProjectid(Integer projectid) {
        this.projectid = projectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_r_partner2project.PARTNERID
     *
     * @return the value of tb_r_partner2project.PARTNERID
     *
     * @mbggenerated
     */
    public Integer getPartnerid() {
        return partnerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_r_partner2project.PARTNERID
     *
     * @param partnerid the value for tb_r_partner2project.PARTNERID
     *
     * @mbggenerated
     */
    public void setPartnerid(Integer partnerid) {
        this.partnerid = partnerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_r_partner2project.STATUS
     *
     * @return the value of tb_r_partner2project.STATUS
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_r_partner2project.STATUS
     *
     * @param status the value for tb_r_partner2project.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_r_partner2project.CHECKTIME
     *
     * @return the value of tb_r_partner2project.CHECKTIME
     *
     * @mbggenerated
     */
    public Date getChecktime() {
        return checktime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_r_partner2project.CHECKTIME
     *
     * @param checktime the value for tb_r_partner2project.CHECKTIME
     *
     * @mbggenerated
     */
    public void setChecktime(Date checktime) {
        this.checktime = checktime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_r_partner2project.CHECKUSERID
     *
     * @return the value of tb_r_partner2project.CHECKUSERID
     *
     * @mbggenerated
     */
    public Integer getCheckuserid() {
        return checkuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_r_partner2project.CHECKUSERID
     *
     * @param checkuserid the value for tb_r_partner2project.CHECKUSERID
     *
     * @mbggenerated
     */
    public void setCheckuserid(Integer checkuserid) {
        this.checkuserid = checkuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_r_partner2project.REMARKS
     *
     * @return the value of tb_r_partner2project.REMARKS
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_r_partner2project.REMARKS
     *
     * @param remarks the value for tb_r_partner2project.REMARKS
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_r_partner2project.DELMARK
     *
     * @return the value of tb_r_partner2project.DELMARK
     *
     * @mbggenerated
     */
    public Integer getDelmark() {
        return delmark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_r_partner2project.DELMARK
     *
     * @param delmark the value for tb_r_partner2project.DELMARK
     *
     * @mbggenerated
     */
    public void setDelmark(Integer delmark) {
        this.delmark = delmark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_r_partner2project.CREATETIME
     *
     * @return the value of tb_r_partner2project.CREATETIME
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_r_partner2project.CREATETIME
     *
     * @param createtime the value for tb_r_partner2project.CREATETIME
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_r_partner2project.CREATEUSERID
     *
     * @return the value of tb_r_partner2project.CREATEUSERID
     *
     * @mbggenerated
     */
    public Integer getCreateuserid() {
        return createuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_r_partner2project.CREATEUSERID
     *
     * @param createuserid the value for tb_r_partner2project.CREATEUSERID
     *
     * @mbggenerated
     */
    public void setCreateuserid(Integer createuserid) {
        this.createuserid = createuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_r_partner2project.MODIFYTIME
     *
     * @return the value of tb_r_partner2project.MODIFYTIME
     *
     * @mbggenerated
     */
    public Date getModifytime() {
        return modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_r_partner2project.MODIFYTIME
     *
     * @param modifytime the value for tb_r_partner2project.MODIFYTIME
     *
     * @mbggenerated
     */
    public void setModifytime(Date modifytime) {
        this.modifytime = modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_r_partner2project.MODIFYUSERID
     *
     * @return the value of tb_r_partner2project.MODIFYUSERID
     *
     * @mbggenerated
     */
    public Integer getModifyuserid() {
        return modifyuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_r_partner2project.MODIFYUSERID
     *
     * @param modifyuserid the value for tb_r_partner2project.MODIFYUSERID
     *
     * @mbggenerated
     */
    public void setModifyuserid(Integer modifyuserid) {
        this.modifyuserid = modifyuserid;
    }
}