package com.unisk.zc.entitys;

import java.util.Date;

public class Projects extends BaseQuery<Projects> {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_d_projects.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_d_projects.PROJECTNAME
     *
     * @mbggenerated
     */
    private String projectname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_d_projects.PROJECTBRIEF
     *
     * @mbggenerated
     */
    private String projectbrief;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_d_projects.PROJECTSTATUS
     *
     * @mbggenerated
     */
    private Integer projectstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_d_projects.PROJECTLOGO
     *
     * @mbggenerated
     */
    private String projectlogo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_d_projects.COVERIMAGE
     *
     * @mbggenerated
     */
    private String coverimage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_d_projects.STARTTIME
     *
     * @mbggenerated
     */
    private Date starttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_d_projects.CROWDTIME
     *
     * @mbggenerated
     */
    private Date crowdtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_d_projects.EXAMINETIME
     *
     * @mbggenerated
     */
    private Date examinetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_d_projects.ENDTIME
     *
     * @mbggenerated
     */
    private Date endtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_d_projects.AGREECOUNT
     *
     * @mbggenerated
     */
    private Integer agreecount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_d_projects.AGAINSTCOUNT
     *
     * @mbggenerated
     */
    private Integer againstcount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_d_projects.ISALLOWEDAGREE
     *
     * @mbggenerated
     */
    private Integer isallowedagree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_d_projects.MAXAGREELIMIT
     *
     * @mbggenerated
     */
    private Integer maxagreelimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_d_projects.PARENTID
     *
     * @mbggenerated
     */
    private String parentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_d_projects.DELMARK
     *
     * @mbggenerated
     */
    private Integer delmark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_d_projects.CREATETIME
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_d_projects.CREATEUSERID
     *
     * @mbggenerated
     */
    private Integer createuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_d_projects.MODIFYTIME
     *
     * @mbggenerated
     */
    private Date modifytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_d_projects.MODIFYUSERID
     *
     * @mbggenerated
     */
    private Integer modifyuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_d_projects.PROJECTCONTENT
     *
     * @mbggenerated
     */
    private String projectcontent;
    
    private String provid;
    
    public String getProvid() {
		return provid;
	}

	public void setProvid(String provid) {
		this.provid = provid;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_d_projects.ID
     *
     * @return the value of tb_d_projects.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_d_projects.ID
     *
     * @param id the value for tb_d_projects.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_d_projects.PROJECTNAME
     *
     * @return the value of tb_d_projects.PROJECTNAME
     *
     * @mbggenerated
     */
    public String getProjectname() {
        return projectname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_d_projects.PROJECTNAME
     *
     * @param projectname the value for tb_d_projects.PROJECTNAME
     *
     * @mbggenerated
     */
    public void setProjectname(String projectname) {
        this.projectname = projectname == null ? null : projectname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_d_projects.PROJECTBRIEF
     *
     * @return the value of tb_d_projects.PROJECTBRIEF
     *
     * @mbggenerated
     */
    public String getProjectbrief() {
        return projectbrief;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_d_projects.PROJECTBRIEF
     *
     * @param projectbrief the value for tb_d_projects.PROJECTBRIEF
     *
     * @mbggenerated
     */
    public void setProjectbrief(String projectbrief) {
        this.projectbrief = projectbrief == null ? null : projectbrief.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_d_projects.PROJECTSTATUS
     *
     * @return the value of tb_d_projects.PROJECTSTATUS
     *
     * @mbggenerated
     */
    public Integer getProjectstatus() {
        return projectstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_d_projects.PROJECTSTATUS
     *
     * @param projectstatus the value for tb_d_projects.PROJECTSTATUS
     *
     * @mbggenerated
     */
    public void setProjectstatus(Integer projectstatus) {
        this.projectstatus = projectstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_d_projects.PROJECTLOGO
     *
     * @return the value of tb_d_projects.PROJECTLOGO
     *
     * @mbggenerated
     */
    public String getProjectlogo() {
        return projectlogo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_d_projects.PROJECTLOGO
     *
     * @param projectlogo the value for tb_d_projects.PROJECTLOGO
     *
     * @mbggenerated
     */
    public void setProjectlogo(String projectlogo) {
        this.projectlogo = projectlogo == null ? null : projectlogo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_d_projects.COVERIMAGE
     *
     * @return the value of tb_d_projects.COVERIMAGE
     *
     * @mbggenerated
     */
    public String getCoverimage() {
        return coverimage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_d_projects.COVERIMAGE
     *
     * @param coverimage the value for tb_d_projects.COVERIMAGE
     *
     * @mbggenerated
     */
    public void setCoverimage(String coverimage) {
        this.coverimage = coverimage == null ? null : coverimage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_d_projects.STARTTIME
     *
     * @return the value of tb_d_projects.STARTTIME
     *
     * @mbggenerated
     */
    public Date getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_d_projects.STARTTIME
     *
     * @param starttime the value for tb_d_projects.STARTTIME
     *
     * @mbggenerated
     */
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_d_projects.CROWDTIME
     *
     * @return the value of tb_d_projects.CROWDTIME
     *
     * @mbggenerated
     */
    public Date getCrowdtime() {
        return crowdtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_d_projects.CROWDTIME
     *
     * @param crowdtime the value for tb_d_projects.CROWDTIME
     *
     * @mbggenerated
     */
    public void setCrowdtime(Date crowdtime) {
        this.crowdtime = crowdtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_d_projects.EXAMINETIME
     *
     * @return the value of tb_d_projects.EXAMINETIME
     *
     * @mbggenerated
     */
    public Date getExaminetime() {
        return examinetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_d_projects.EXAMINETIME
     *
     * @param examinetime the value for tb_d_projects.EXAMINETIME
     *
     * @mbggenerated
     */
    public void setExaminetime(Date examinetime) {
        this.examinetime = examinetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_d_projects.ENDTIME
     *
     * @return the value of tb_d_projects.ENDTIME
     *
     * @mbggenerated
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_d_projects.ENDTIME
     *
     * @param endtime the value for tb_d_projects.ENDTIME
     *
     * @mbggenerated
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_d_projects.AGREECOUNT
     *
     * @return the value of tb_d_projects.AGREECOUNT
     *
     * @mbggenerated
     */
    public Integer getAgreecount() {
        return agreecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_d_projects.AGREECOUNT
     *
     * @param agreecount the value for tb_d_projects.AGREECOUNT
     *
     * @mbggenerated
     */
    public void setAgreecount(Integer agreecount) {
        this.agreecount = agreecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_d_projects.AGAINSTCOUNT
     *
     * @return the value of tb_d_projects.AGAINSTCOUNT
     *
     * @mbggenerated
     */
    public Integer getAgainstcount() {
        return againstcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_d_projects.AGAINSTCOUNT
     *
     * @param againstcount the value for tb_d_projects.AGAINSTCOUNT
     *
     * @mbggenerated
     */
    public void setAgainstcount(Integer againstcount) {
        this.againstcount = againstcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_d_projects.ISALLOWEDAGREE
     *
     * @return the value of tb_d_projects.ISALLOWEDAGREE
     *
     * @mbggenerated
     */
    public Integer getIsallowedagree() {
        return isallowedagree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_d_projects.ISALLOWEDAGREE
     *
     * @param isallowedagree the value for tb_d_projects.ISALLOWEDAGREE
     *
     * @mbggenerated
     */
    public void setIsallowedagree(Integer isallowedagree) {
        this.isallowedagree = isallowedagree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_d_projects.MAXAGREELIMIT
     *
     * @return the value of tb_d_projects.MAXAGREELIMIT
     *
     * @mbggenerated
     */
    public Integer getMaxagreelimit() {
        return maxagreelimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_d_projects.MAXAGREELIMIT
     *
     * @param maxagreelimit the value for tb_d_projects.MAXAGREELIMIT
     *
     * @mbggenerated
     */
    public void setMaxagreelimit(Integer maxagreelimit) {
        this.maxagreelimit = maxagreelimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_d_projects.PARENTID
     *
     * @return the value of tb_d_projects.PARENTID
     *
     * @mbggenerated
     */
    public String getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_d_projects.PARENTID
     *
     * @param parentid the value for tb_d_projects.PARENTID
     *
     * @mbggenerated
     */
    public void setParentid(String parentid) {
        this.parentid = parentid == null ? null : parentid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_d_projects.DELMARK
     *
     * @return the value of tb_d_projects.DELMARK
     *
     * @mbggenerated
     */
    public Integer getDelmark() {
        return delmark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_d_projects.DELMARK
     *
     * @param delmark the value for tb_d_projects.DELMARK
     *
     * @mbggenerated
     */
    public void setDelmark(Integer delmark) {
        this.delmark = delmark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_d_projects.CREATETIME
     *
     * @return the value of tb_d_projects.CREATETIME
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_d_projects.CREATETIME
     *
     * @param createtime the value for tb_d_projects.CREATETIME
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_d_projects.CREATEUSERID
     *
     * @return the value of tb_d_projects.CREATEUSERID
     *
     * @mbggenerated
     */
    public Integer getCreateuserid() {
        return createuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_d_projects.CREATEUSERID
     *
     * @param createuserid the value for tb_d_projects.CREATEUSERID
     *
     * @mbggenerated
     */
    public void setCreateuserid(Integer createuserid) {
        this.createuserid = createuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_d_projects.MODIFYTIME
     *
     * @return the value of tb_d_projects.MODIFYTIME
     *
     * @mbggenerated
     */
    public Date getModifytime() {
        return modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_d_projects.MODIFYTIME
     *
     * @param modifytime the value for tb_d_projects.MODIFYTIME
     *
     * @mbggenerated
     */
    public void setModifytime(Date modifytime) {
        this.modifytime = modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_d_projects.MODIFYUSERID
     *
     * @return the value of tb_d_projects.MODIFYUSERID
     *
     * @mbggenerated
     */
    public Integer getModifyuserid() {
        return modifyuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_d_projects.MODIFYUSERID
     *
     * @param modifyuserid the value for tb_d_projects.MODIFYUSERID
     *
     * @mbggenerated
     */
    public void setModifyuserid(Integer modifyuserid) {
        this.modifyuserid = modifyuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_d_projects.PROJECTCONTENT
     *
     * @return the value of tb_d_projects.PROJECTCONTENT
     *
     * @mbggenerated
     */
    public String getProjectcontent() {
        return projectcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_d_projects.PROJECTCONTENT
     *
     * @param projectcontent the value for tb_d_projects.PROJECTCONTENT
     *
     * @mbggenerated
     */
    public void setProjectcontent(String projectcontent) {
        this.projectcontent = projectcontent == null ? null : projectcontent.trim();
    }
}