package com.unisk.zc.entitys;

public class RegionCode extends BaseQuery<RegionCode> {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_D_REGION_CODE.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_D_REGION_CODE.ID
     *
     * @return the value of TB_D_REGION_CODE.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_D_REGION_CODE.ID
     *
     * @param id the value for TB_D_REGION_CODE.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }
}