package com.unisk.zc.entitys;

import java.util.Date;

public class SubjectAndRoles extends BaseQuery<SubjectAndRoles> {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_R_SUBJECT_AND_ROLES.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_R_SUBJECT_AND_ROLES.MASTER
     *
     * @mbggenerated
     */
    private String master;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_R_SUBJECT_AND_ROLES.MASTERVALUE
     *
     * @mbggenerated
     */
    private Integer mastervalue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_R_SUBJECT_AND_ROLES.ROLEID
     *
     * @mbggenerated
     */
    private Integer roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_R_SUBJECT_AND_ROLES.REMARKS
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_R_SUBJECT_AND_ROLES.DELMARK
     *
     * @mbggenerated
     */
    private Integer delmark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_R_SUBJECT_AND_ROLES.CREATETIME
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_R_SUBJECT_AND_ROLES.CREATEUSERID
     *
     * @mbggenerated
     */
    private Integer createuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_R_SUBJECT_AND_ROLES.MODIFYTIME
     *
     * @mbggenerated
     */
    private Date modifytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_R_SUBJECT_AND_ROLES.MODIFYUSERID
     *
     * @mbggenerated
     */
    private Integer modifyuserid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_R_SUBJECT_AND_ROLES.ID
     *
     * @return the value of TB_R_SUBJECT_AND_ROLES.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_R_SUBJECT_AND_ROLES.ID
     *
     * @param id the value for TB_R_SUBJECT_AND_ROLES.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_R_SUBJECT_AND_ROLES.MASTER
     *
     * @return the value of TB_R_SUBJECT_AND_ROLES.MASTER
     *
     * @mbggenerated
     */
    public String getMaster() {
        return master;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_R_SUBJECT_AND_ROLES.MASTER
     *
     * @param master the value for TB_R_SUBJECT_AND_ROLES.MASTER
     *
     * @mbggenerated
     */
    public void setMaster(String master) {
        this.master = master == null ? null : master.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_R_SUBJECT_AND_ROLES.MASTERVALUE
     *
     * @return the value of TB_R_SUBJECT_AND_ROLES.MASTERVALUE
     *
     * @mbggenerated
     */
    public Integer getMastervalue() {
        return mastervalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_R_SUBJECT_AND_ROLES.MASTERVALUE
     *
     * @param mastervalue the value for TB_R_SUBJECT_AND_ROLES.MASTERVALUE
     *
     * @mbggenerated
     */
    public void setMastervalue(Integer mastervalue) {
        this.mastervalue = mastervalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_R_SUBJECT_AND_ROLES.ROLEID
     *
     * @return the value of TB_R_SUBJECT_AND_ROLES.ROLEID
     *
     * @mbggenerated
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_R_SUBJECT_AND_ROLES.ROLEID
     *
     * @param roleid the value for TB_R_SUBJECT_AND_ROLES.ROLEID
     *
     * @mbggenerated
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_R_SUBJECT_AND_ROLES.REMARKS
     *
     * @return the value of TB_R_SUBJECT_AND_ROLES.REMARKS
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_R_SUBJECT_AND_ROLES.REMARKS
     *
     * @param remarks the value for TB_R_SUBJECT_AND_ROLES.REMARKS
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_R_SUBJECT_AND_ROLES.DELMARK
     *
     * @return the value of TB_R_SUBJECT_AND_ROLES.DELMARK
     *
     * @mbggenerated
     */
    public Integer getDelmark() {
        return delmark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_R_SUBJECT_AND_ROLES.DELMARK
     *
     * @param delmark the value for TB_R_SUBJECT_AND_ROLES.DELMARK
     *
     * @mbggenerated
     */
    public void setDelmark(Integer delmark) {
        this.delmark = delmark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_R_SUBJECT_AND_ROLES.CREATETIME
     *
     * @return the value of TB_R_SUBJECT_AND_ROLES.CREATETIME
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_R_SUBJECT_AND_ROLES.CREATETIME
     *
     * @param createtime the value for TB_R_SUBJECT_AND_ROLES.CREATETIME
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_R_SUBJECT_AND_ROLES.CREATEUSERID
     *
     * @return the value of TB_R_SUBJECT_AND_ROLES.CREATEUSERID
     *
     * @mbggenerated
     */
    public Integer getCreateuserid() {
        return createuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_R_SUBJECT_AND_ROLES.CREATEUSERID
     *
     * @param createuserid the value for TB_R_SUBJECT_AND_ROLES.CREATEUSERID
     *
     * @mbggenerated
     */
    public void setCreateuserid(Integer createuserid) {
        this.createuserid = createuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_R_SUBJECT_AND_ROLES.MODIFYTIME
     *
     * @return the value of TB_R_SUBJECT_AND_ROLES.MODIFYTIME
     *
     * @mbggenerated
     */
    public Date getModifytime() {
        return modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_R_SUBJECT_AND_ROLES.MODIFYTIME
     *
     * @param modifytime the value for TB_R_SUBJECT_AND_ROLES.MODIFYTIME
     *
     * @mbggenerated
     */
    public void setModifytime(Date modifytime) {
        this.modifytime = modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_R_SUBJECT_AND_ROLES.MODIFYUSERID
     *
     * @return the value of TB_R_SUBJECT_AND_ROLES.MODIFYUSERID
     *
     * @mbggenerated
     */
    public Integer getModifyuserid() {
        return modifyuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_R_SUBJECT_AND_ROLES.MODIFYUSERID
     *
     * @param modifyuserid the value for TB_R_SUBJECT_AND_ROLES.MODIFYUSERID
     *
     * @mbggenerated
     */
    public void setModifyuserid(Integer modifyuserid) {
        this.modifyuserid = modifyuserid;
    }
}