package com.unisk.zc.entitys;

import java.util.Date;

public class UserAndUserGroup extends BaseQuery<UserAndUserGroup> {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column TB_R_USER_AND_USERGROUP.ID
	 *
	 * @mbggenerated
	 */
	private Integer id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column TB_R_USER_AND_USERGROUP.USERID
	 *
	 * @mbggenerated
	 */
	private Integer userid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column TB_R_USER_AND_USERGROUP.USERGROUPID
	 *
	 * @mbggenerated
	 */
	private Integer usergroupid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column TB_R_USER_AND_USERGROUP.DELMARK
	 *
	 * @mbggenerated
	 */
	private Integer delmark;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column TB_R_USER_AND_USERGROUP.CREATETIME
	 *
	 * @mbggenerated
	 */
	private Date createtime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column TB_R_USER_AND_USERGROUP.CREATEUSERID
	 *
	 * @mbggenerated
	 */
	private Integer createuserid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column TB_R_USER_AND_USERGROUP.MODIFYTIME
	 *
	 * @mbggenerated
	 */
	private Date modifytime;

	private Integer wechatstatus;
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column TB_R_USER_AND_USERGROUP.MODIFYUSERID
	 *
	 * @mbggenerated
	 */
	private Integer modifyuserid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column TB_R_USER_AND_USERGROUP.ID
	 *
	 * @return the value of TB_R_USER_AND_USERGROUP.ID
	 *
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column TB_R_USER_AND_USERGROUP.ID
	 *
	 * @param id
	 *            the value for TB_R_USER_AND_USERGROUP.ID
	 *
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column TB_R_USER_AND_USERGROUP.USERID
	 *
	 * @return the value of TB_R_USER_AND_USERGROUP.USERID
	 *
	 * @mbggenerated
	 */
	public Integer getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column TB_R_USER_AND_USERGROUP.USERID
	 *
	 * @param userid
	 *            the value for TB_R_USER_AND_USERGROUP.USERID
	 *
	 * @mbggenerated
	 */
	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column TB_R_USER_AND_USERGROUP.USERGROUPID
	 *
	 * @return the value of TB_R_USER_AND_USERGROUP.USERGROUPID
	 *
	 * @mbggenerated
	 */
	public Integer getUsergroupid() {
		return usergroupid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column TB_R_USER_AND_USERGROUP.USERGROUPID
	 *
	 * @param usergroupid
	 *            the value for TB_R_USER_AND_USERGROUP.USERGROUPID
	 *
	 * @mbggenerated
	 */
	public void setUsergroupid(Integer usergroupid) {
		this.usergroupid = usergroupid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column TB_R_USER_AND_USERGROUP.DELMARK
	 *
	 * @return the value of TB_R_USER_AND_USERGROUP.DELMARK
	 *
	 * @mbggenerated
	 */
	public Integer getDelmark() {
		return delmark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column TB_R_USER_AND_USERGROUP.DELMARK
	 *
	 * @param delmark
	 *            the value for TB_R_USER_AND_USERGROUP.DELMARK
	 *
	 * @mbggenerated
	 */
	public void setDelmark(Integer delmark) {
		this.delmark = delmark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column TB_R_USER_AND_USERGROUP.CREATETIME
	 *
	 * @return the value of TB_R_USER_AND_USERGROUP.CREATETIME
	 *
	 * @mbggenerated
	 */
	public Date getCreatetime() {
		return createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column TB_R_USER_AND_USERGROUP.CREATETIME
	 *
	 * @param createtime
	 *            the value for TB_R_USER_AND_USERGROUP.CREATETIME
	 *
	 * @mbggenerated
	 */
	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column TB_R_USER_AND_USERGROUP.CREATEUSERID
	 *
	 * @return the value of TB_R_USER_AND_USERGROUP.CREATEUSERID
	 *
	 * @mbggenerated
	 */
	public Integer getCreateuserid() {
		return createuserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column TB_R_USER_AND_USERGROUP.CREATEUSERID
	 *
	 * @param createuserid
	 *            the value for TB_R_USER_AND_USERGROUP.CREATEUSERID
	 *
	 * @mbggenerated
	 */
	public void setCreateuserid(Integer createuserid) {
		this.createuserid = createuserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column TB_R_USER_AND_USERGROUP.MODIFYTIME
	 *
	 * @return the value of TB_R_USER_AND_USERGROUP.MODIFYTIME
	 *
	 * @mbggenerated
	 */
	public Date getModifytime() {
		return modifytime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column TB_R_USER_AND_USERGROUP.MODIFYTIME
	 *
	 * @param modifytime
	 *            the value for TB_R_USER_AND_USERGROUP.MODIFYTIME
	 *
	 * @mbggenerated
	 */
	public void setModifytime(Date modifytime) {
		this.modifytime = modifytime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column TB_R_USER_AND_USERGROUP.MODIFYUSERID
	 *
	 * @return the value of TB_R_USER_AND_USERGROUP.MODIFYUSERID
	 *
	 * @mbggenerated
	 */
	public Integer getModifyuserid() {
		return modifyuserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column TB_R_USER_AND_USERGROUP.MODIFYUSERID
	 *
	 * @param modifyuserid
	 *            the value for TB_R_USER_AND_USERGROUP.MODIFYUSERID
	 *
	 * @mbggenerated
	 */
	public void setModifyuserid(Integer modifyuserid) {
		this.modifyuserid = modifyuserid;
	}

	public Integer getWechatstatus() {
		return wechatstatus;
	}

	public void setWechatstatus(Integer wechatstatus) {
		this.wechatstatus = wechatstatus;
	}
}