package com.unisk.zc.entitys;

import java.util.Date;

public class UserGroup extends BaseQuery<UserGroup> {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_D_USERGROUP.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_D_USERGROUP.GROUPNAME
     *
     * @mbggenerated
     */
    private String groupname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_D_USERGROUP.PARENTID
     *
     * @mbggenerated
     */
    private Integer parentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_D_USERGROUP.GROUPNO
     *
     * @mbggenerated
     */
    private String groupno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_D_USERGROUP.ALLOWDEL
     *
     * @mbggenerated
     */
    private Integer allowdel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_D_USERGROUP.ALLOWEDIT
     *
     * @mbggenerated
     */
    private Integer allowedit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_D_USERGROUP.SORTCODE
     *
     * @mbggenerated
     */
    private Integer sortcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_D_USERGROUP.REMARKS
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_D_USERGROUP.DELMARK
     *
     * @mbggenerated
     */
    private Integer delmark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_D_USERGROUP.CREATETIME
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_D_USERGROUP.CREATEUSERID
     *
     * @mbggenerated
     */
    private Integer createuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_D_USERGROUP.MODIFYTIME
     *
     * @mbggenerated
     */
    private Date modifytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_D_USERGROUP.MODIFYUSERID
     *
     * @mbggenerated
     */
    private Integer modifyuserid;

    private Integer wechatstatus;
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_D_USERGROUP.ID
     *
     * @return the value of TB_D_USERGROUP.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_D_USERGROUP.ID
     *
     * @param id the value for TB_D_USERGROUP.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_D_USERGROUP.GROUPNAME
     *
     * @return the value of TB_D_USERGROUP.GROUPNAME
     *
     * @mbggenerated
     */
    public String getGroupname() {
        return groupname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_D_USERGROUP.GROUPNAME
     *
     * @param groupname the value for TB_D_USERGROUP.GROUPNAME
     *
     * @mbggenerated
     */
    public void setGroupname(String groupname) {
        this.groupname = groupname == null ? null : groupname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_D_USERGROUP.PARENTID
     *
     * @return the value of TB_D_USERGROUP.PARENTID
     *
     * @mbggenerated
     */
    public Integer getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_D_USERGROUP.PARENTID
     *
     * @param parentid the value for TB_D_USERGROUP.PARENTID
     *
     * @mbggenerated
     */
    public void setParentid(Integer parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_D_USERGROUP.GROUPNO
     *
     * @return the value of TB_D_USERGROUP.GROUPNO
     *
     * @mbggenerated
     */
    public String getGroupno() {
        return groupno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_D_USERGROUP.GROUPNO
     *
     * @param groupno the value for TB_D_USERGROUP.GROUPNO
     *
     * @mbggenerated
     */
    public void setGroupno(String groupno) {
        this.groupno = groupno == null ? null : groupno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_D_USERGROUP.ALLOWDEL
     *
     * @return the value of TB_D_USERGROUP.ALLOWDEL
     *
     * @mbggenerated
     */
    public Integer getAllowdel() {
        return allowdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_D_USERGROUP.ALLOWDEL
     *
     * @param allowdel the value for TB_D_USERGROUP.ALLOWDEL
     *
     * @mbggenerated
     */
    public void setAllowdel(Integer allowdel) {
        this.allowdel = allowdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_D_USERGROUP.ALLOWEDIT
     *
     * @return the value of TB_D_USERGROUP.ALLOWEDIT
     *
     * @mbggenerated
     */
    public Integer getAllowedit() {
        return allowedit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_D_USERGROUP.ALLOWEDIT
     *
     * @param allowedit the value for TB_D_USERGROUP.ALLOWEDIT
     *
     * @mbggenerated
     */
    public void setAllowedit(Integer allowedit) {
        this.allowedit = allowedit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_D_USERGROUP.SORTCODE
     *
     * @return the value of TB_D_USERGROUP.SORTCODE
     *
     * @mbggenerated
     */
    public Integer getSortcode() {
        return sortcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_D_USERGROUP.SORTCODE
     *
     * @param sortcode the value for TB_D_USERGROUP.SORTCODE
     *
     * @mbggenerated
     */
    public void setSortcode(Integer sortcode) {
        this.sortcode = sortcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_D_USERGROUP.REMARKS
     *
     * @return the value of TB_D_USERGROUP.REMARKS
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_D_USERGROUP.REMARKS
     *
     * @param remarks the value for TB_D_USERGROUP.REMARKS
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_D_USERGROUP.DELMARK
     *
     * @return the value of TB_D_USERGROUP.DELMARK
     *
     * @mbggenerated
     */
    public Integer getDelmark() {
        return delmark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_D_USERGROUP.DELMARK
     *
     * @param delmark the value for TB_D_USERGROUP.DELMARK
     *
     * @mbggenerated
     */
    public void setDelmark(Integer delmark) {
        this.delmark = delmark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_D_USERGROUP.CREATETIME
     *
     * @return the value of TB_D_USERGROUP.CREATETIME
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_D_USERGROUP.CREATETIME
     *
     * @param createtime the value for TB_D_USERGROUP.CREATETIME
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_D_USERGROUP.CREATEUSERID
     *
     * @return the value of TB_D_USERGROUP.CREATEUSERID
     *
     * @mbggenerated
     */
    public Integer getCreateuserid() {
        return createuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_D_USERGROUP.CREATEUSERID
     *
     * @param createuserid the value for TB_D_USERGROUP.CREATEUSERID
     *
     * @mbggenerated
     */
    public void setCreateuserid(Integer createuserid) {
        this.createuserid = createuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_D_USERGROUP.MODIFYTIME
     *
     * @return the value of TB_D_USERGROUP.MODIFYTIME
     *
     * @mbggenerated
     */
    public Date getModifytime() {
        return modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_D_USERGROUP.MODIFYTIME
     *
     * @param modifytime the value for TB_D_USERGROUP.MODIFYTIME
     *
     * @mbggenerated
     */
    public void setModifytime(Date modifytime) {
        this.modifytime = modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_D_USERGROUP.MODIFYUSERID
     *
     * @return the value of TB_D_USERGROUP.MODIFYUSERID
     *
     * @mbggenerated
     */
    public Integer getModifyuserid() {
        return modifyuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_D_USERGROUP.MODIFYUSERID
     *
     * @param modifyuserid the value for TB_D_USERGROUP.MODIFYUSERID
     *
     * @mbggenerated
     */
    public void setModifyuserid(Integer modifyuserid) {
        this.modifyuserid = modifyuserid;
    }

	public Integer getWechatstatus() {
		return wechatstatus;
	}

	public void setWechatstatus(Integer wechatstatus) {
		this.wechatstatus = wechatstatus;
	}
    
}