package com.unisk.zc.entitys;

import java.util.Date;

public class Vote extends BaseQuery<Vote>{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_d_vote.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_d_vote.TITLE
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_d_vote.DEADLINETIME
     *
     * @mbggenerated
     */
    private String deadlinetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_d_vote.ISALL
     *
     * @mbggenerated
     */
    private Integer isall;
    
    /**
     * 投票对象
     */
    private String touserlabel;
    
    /**
     * 投票对象ID字符串
     */
    private String touserids;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_d_vote.HEADCONTENT
     *
     * @mbggenerated
     */
    private String headcontent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_d_vote.FOOTERCONTENT
     *
     * @mbggenerated
     */
    private String footercontent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_d_vote.ALLOWSHOWRESULT
     *
     * @mbggenerated
     */
    private Integer allowshowresult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_d_vote.ALLOWANONYMAT
     *
     * @mbggenerated
     */
    private Integer allowanonymat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_d_vote.FROMUSERID
     *
     * @mbggenerated
     */
    private Integer fromuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_d_vote.STATUS
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_d_vote.REMARKS
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_d_vote.DELMARK
     *
     * @mbggenerated
     */
    private Byte delmark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_d_vote.CREATETIME
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_d_vote.MODIFYTIME
     *
     * @mbggenerated
     */
    private Date modifytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_d_vote.CREATEUSERID
     *
     * @mbggenerated
     */
    private Integer createuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_d_vote.MODIFYUSERID
     *
     * @mbggenerated
     */
    private Integer modifyuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_d_vote.VOTEURL
     *
     * @mbggenerated
     */
    private String voteurl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_d_vote.ID
     *
     * @return the value of tb_d_vote.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_d_vote.ID
     *
     * @param id the value for tb_d_vote.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_d_vote.TITLE
     *
     * @return the value of tb_d_vote.TITLE
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_d_vote.TITLE
     *
     * @param title the value for tb_d_vote.TITLE
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_d_vote.DEADLINETIME
     *
     * @return the value of tb_d_vote.DEADLINETIME
     *
     * @mbggenerated
     */
    public String getDeadlinetime() {
        return deadlinetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_d_vote.DEADLINETIME
     *
     * @param deadlinetime the value for tb_d_vote.DEADLINETIME
     *
     * @mbggenerated
     */
    public void setDeadlinetime(String deadlinetime) {
        this.deadlinetime = deadlinetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_d_vote.ISALL
     *
     * @return the value of tb_d_vote.ISALL
     *
     * @mbggenerated
     */
    public Integer getIsall() {
        return isall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_d_vote.ISALL
     *
     * @param isall the value for tb_d_vote.ISALL
     *
     * @mbggenerated
     */
    public void setIsall(Integer isall) {
        this.isall = isall;
    }

    public String getTouserlabel() {
		return touserlabel;
	}

	public void setTouserlabel(String touserlabel) {
		this.touserlabel = touserlabel;
	}

	public String getTouserids() {
		return touserids;
	}

	public void setTouserids(String touserids) {
		this.touserids = touserids;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_d_vote.HEADCONTENT
     *
     * @return the value of tb_d_vote.HEADCONTENT
     *
     * @mbggenerated
     */
    public String getHeadcontent() {
        return headcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_d_vote.HEADCONTENT
     *
     * @param headcontent the value for tb_d_vote.HEADCONTENT
     *
     * @mbggenerated
     */
    public void setHeadcontent(String headcontent) {
        this.headcontent = headcontent == null ? null : headcontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_d_vote.FOOTERCONTENT
     *
     * @return the value of tb_d_vote.FOOTERCONTENT
     *
     * @mbggenerated
     */
    public String getFootercontent() {
        return footercontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_d_vote.FOOTERCONTENT
     *
     * @param footercontent the value for tb_d_vote.FOOTERCONTENT
     *
     * @mbggenerated
     */
    public void setFootercontent(String footercontent) {
        this.footercontent = footercontent == null ? null : footercontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_d_vote.ALLOWSHOWRESULT
     *
     * @return the value of tb_d_vote.ALLOWSHOWRESULT
     *
     * @mbggenerated
     */
    public Integer getAllowshowresult() {
        return allowshowresult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_d_vote.ALLOWSHOWRESULT
     *
     * @param allowshowresult the value for tb_d_vote.ALLOWSHOWRESULT
     *
     * @mbggenerated
     */
    public void setAllowshowresult(Integer allowshowresult) {
        this.allowshowresult = allowshowresult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_d_vote.ALLOWANONYMAT
     *
     * @return the value of tb_d_vote.ALLOWANONYMAT
     *
     * @mbggenerated
     */
    public Integer getAllowanonymat() {
        return allowanonymat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_d_vote.ALLOWANONYMAT
     *
     * @param allowanonymat the value for tb_d_vote.ALLOWANONYMAT
     *
     * @mbggenerated
     */
    public void setAllowanonymat(Integer allowanonymat) {
        this.allowanonymat = allowanonymat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_d_vote.FROMUSERID
     *
     * @return the value of tb_d_vote.FROMUSERID
     *
     * @mbggenerated
     */
    public Integer getFromuserid() {
        return fromuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_d_vote.FROMUSERID
     *
     * @param fromuserid the value for tb_d_vote.FROMUSERID
     *
     * @mbggenerated
     */
    public void setFromuserid(Integer fromuserid) {
        this.fromuserid = fromuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_d_vote.STATUS
     *
     * @return the value of tb_d_vote.STATUS
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_d_vote.STATUS
     *
     * @param status the value for tb_d_vote.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_d_vote.REMARKS
     *
     * @return the value of tb_d_vote.REMARKS
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_d_vote.REMARKS
     *
     * @param remarks the value for tb_d_vote.REMARKS
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_d_vote.DELMARK
     *
     * @return the value of tb_d_vote.DELMARK
     *
     * @mbggenerated
     */
    public Byte getDelmark() {
        return delmark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_d_vote.DELMARK
     *
     * @param delmark the value for tb_d_vote.DELMARK
     *
     * @mbggenerated
     */
    public void setDelmark(Byte delmark) {
        this.delmark = delmark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_d_vote.CREATETIME
     *
     * @return the value of tb_d_vote.CREATETIME
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_d_vote.CREATETIME
     *
     * @param createtime the value for tb_d_vote.CREATETIME
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_d_vote.MODIFYTIME
     *
     * @return the value of tb_d_vote.MODIFYTIME
     *
     * @mbggenerated
     */
    public Date getModifytime() {
        return modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_d_vote.MODIFYTIME
     *
     * @param modifytime the value for tb_d_vote.MODIFYTIME
     *
     * @mbggenerated
     */
    public void setModifytime(Date modifytime) {
        this.modifytime = modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_d_vote.CREATEUSERID
     *
     * @return the value of tb_d_vote.CREATEUSERID
     *
     * @mbggenerated
     */
    public Integer getCreateuserid() {
        return createuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_d_vote.CREATEUSERID
     *
     * @param createuserid the value for tb_d_vote.CREATEUSERID
     *
     * @mbggenerated
     */
    public void setCreateuserid(Integer createuserid) {
        this.createuserid = createuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_d_vote.MODIFYUSERID
     *
     * @return the value of tb_d_vote.MODIFYUSERID
     *
     * @mbggenerated
     */
    public Integer getModifyuserid() {
        return modifyuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_d_vote.MODIFYUSERID
     *
     * @param modifyuserid the value for tb_d_vote.MODIFYUSERID
     *
     * @mbggenerated
     */
    public void setModifyuserid(Integer modifyuserid) {
        this.modifyuserid = modifyuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_d_vote.VOTEURL
     *
     * @return the value of tb_d_vote.VOTEURL
     *
     * @mbggenerated
     */
    public String getVoteurl() {
        return voteurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_d_vote.VOTEURL
     *
     * @param voteurl the value for tb_d_vote.VOTEURL
     *
     * @mbggenerated
     */
    public void setVoteurl(String voteurl) {
        this.voteurl = voteurl == null ? null : voteurl.trim();
    }
}