package com.unisk.zc.entitys;

import java.util.Date;

public class VoteTopic extends BaseQuery<VoteTopic>{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_d_vote_topic.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_d_vote_topic.VOTEID
     *
     * @mbggenerated
     */
    private Integer voteid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_d_vote_topic.KINDS
     *
     * @mbggenerated
     */
    private Integer kinds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_d_vote_topic.TITLE
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_d_vote_topic.MAXVOTE
     *
     * @mbggenerated
     */
    private Integer maxvote;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_d_vote_topic.MIXVOTE
     *
     * @mbggenerated
     */
    private Integer mixvote;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_d_vote_topic.ALLOWUSERDEFINE
     *
     * @mbggenerated
     */
    private Integer allowuserdefine;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_d_vote_topic.SORTCODE
     *
     * @mbggenerated
     */
    private Integer sortcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_d_vote_topic.REMARKS
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_d_vote_topic.DELMARK
     *
     * @mbggenerated
     */
    private Integer delmark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_d_vote_topic.CREATETIME
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_d_vote_topic.MODIFYTIME
     *
     * @mbggenerated
     */
    private Date modifytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_d_vote_topic.CREATEUSERID
     *
     * @mbggenerated
     */
    private Integer createuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_d_vote_topic.MODIFYUSERID
     *
     * @mbggenerated
     */
    private Integer modifyuserid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_d_vote_topic.ID
     *
     * @return the value of tb_d_vote_topic.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_d_vote_topic.ID
     *
     * @param id the value for tb_d_vote_topic.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_d_vote_topic.VOTEID
     *
     * @return the value of tb_d_vote_topic.VOTEID
     *
     * @mbggenerated
     */
    public Integer getVoteid() {
        return voteid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_d_vote_topic.VOTEID
     *
     * @param voteid the value for tb_d_vote_topic.VOTEID
     *
     * @mbggenerated
     */
    public void setVoteid(Integer voteid) {
        this.voteid = voteid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_d_vote_topic.KINDS
     *
     * @return the value of tb_d_vote_topic.KINDS
     *
     * @mbggenerated
     */
    public Integer getKinds() {
        return kinds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_d_vote_topic.KINDS
     *
     * @param kinds the value for tb_d_vote_topic.KINDS
     *
     * @mbggenerated
     */
    public void setKinds(Integer kinds) {
        this.kinds = kinds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_d_vote_topic.TITLE
     *
     * @return the value of tb_d_vote_topic.TITLE
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_d_vote_topic.TITLE
     *
     * @param title the value for tb_d_vote_topic.TITLE
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_d_vote_topic.MAXVOTE
     *
     * @return the value of tb_d_vote_topic.MAXVOTE
     *
     * @mbggenerated
     */
    public Integer getMaxvote() {
        return maxvote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_d_vote_topic.MAXVOTE
     *
     * @param maxvote the value for tb_d_vote_topic.MAXVOTE
     *
     * @mbggenerated
     */
    public void setMaxvote(Integer maxvote) {
        this.maxvote = maxvote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_d_vote_topic.MIXVOTE
     *
     * @return the value of tb_d_vote_topic.MIXVOTE
     *
     * @mbggenerated
     */
    public Integer getMixvote() {
        return mixvote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_d_vote_topic.MIXVOTE
     *
     * @param mixvote the value for tb_d_vote_topic.MIXVOTE
     *
     * @mbggenerated
     */
    public void setMixvote(Integer mixvote) {
        this.mixvote = mixvote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_d_vote_topic.ALLOWUSERDEFINE
     *
     * @return the value of tb_d_vote_topic.ALLOWUSERDEFINE
     *
     * @mbggenerated
     */
    public Integer getAllowuserdefine() {
        return allowuserdefine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_d_vote_topic.ALLOWUSERDEFINE
     *
     * @param allowuserdefine the value for tb_d_vote_topic.ALLOWUSERDEFINE
     *
     * @mbggenerated
     */
    public void setAllowuserdefine(Integer allowuserdefine) {
        this.allowuserdefine = allowuserdefine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_d_vote_topic.SORTCODE
     *
     * @return the value of tb_d_vote_topic.SORTCODE
     *
     * @mbggenerated
     */
    public Integer getSortcode() {
        return sortcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_d_vote_topic.SORTCODE
     *
     * @param sortcode the value for tb_d_vote_topic.SORTCODE
     *
     * @mbggenerated
     */
    public void setSortcode(Integer sortcode) {
        this.sortcode = sortcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_d_vote_topic.REMARKS
     *
     * @return the value of tb_d_vote_topic.REMARKS
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_d_vote_topic.REMARKS
     *
     * @param remarks the value for tb_d_vote_topic.REMARKS
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_d_vote_topic.DELMARK
     *
     * @return the value of tb_d_vote_topic.DELMARK
     *
     * @mbggenerated
     */
    public Integer getDelmark() {
        return delmark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_d_vote_topic.DELMARK
     *
     * @param delmark the value for tb_d_vote_topic.DELMARK
     *
     * @mbggenerated
     */
    public void setDelmark(Integer delmark) {
        this.delmark = delmark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_d_vote_topic.CREATETIME
     *
     * @return the value of tb_d_vote_topic.CREATETIME
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_d_vote_topic.CREATETIME
     *
     * @param createtime the value for tb_d_vote_topic.CREATETIME
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_d_vote_topic.MODIFYTIME
     *
     * @return the value of tb_d_vote_topic.MODIFYTIME
     *
     * @mbggenerated
     */
    public Date getModifytime() {
        return modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_d_vote_topic.MODIFYTIME
     *
     * @param modifytime the value for tb_d_vote_topic.MODIFYTIME
     *
     * @mbggenerated
     */
    public void setModifytime(Date modifytime) {
        this.modifytime = modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_d_vote_topic.CREATEUSERID
     *
     * @return the value of tb_d_vote_topic.CREATEUSERID
     *
     * @mbggenerated
     */
    public Integer getCreateuserid() {
        return createuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_d_vote_topic.CREATEUSERID
     *
     * @param createuserid the value for tb_d_vote_topic.CREATEUSERID
     *
     * @mbggenerated
     */
    public void setCreateuserid(Integer createuserid) {
        this.createuserid = createuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_d_vote_topic.MODIFYUSERID
     *
     * @return the value of tb_d_vote_topic.MODIFYUSERID
     *
     * @mbggenerated
     */
    public Integer getModifyuserid() {
        return modifyuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_d_vote_topic.MODIFYUSERID
     *
     * @param modifyuserid the value for tb_d_vote_topic.MODIFYUSERID
     *
     * @mbggenerated
     */
    public void setModifyuserid(Integer modifyuserid) {
        this.modifyuserid = modifyuserid;
    }
}