package com.unisk.zc.entitys;

import java.util.Date;

public class VoteResult extends BaseQuery<VoteResult>{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_d_vote_result.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_d_vote_result.VOTEID
     *
     * @mbggenerated
     */
    private Integer voteid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_d_vote_result.TOPICID
     *
     * @mbggenerated
     */
    private Integer topicid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_d_vote_result.OPTIONID
     *
     * @mbggenerated
     */
    private Integer optionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_d_vote_result.OPTIONEXTID
     *
     * @mbggenerated
     */
    private Integer optionextid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_d_vote_result.ALLOWANONYMITY
     *
     * @mbggenerated
     */
    private Byte allowanonymity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_d_vote_result.VOTEUSERID
     *
     * @mbggenerated
     */
    private Integer voteuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_d_vote_result.REMARKS
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_d_vote_result.DELMARK
     *
     * @mbggenerated
     */
    private Byte delmark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_d_vote_result.CREATETIME
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_d_vote_result.MODIFYTIME
     *
     * @mbggenerated
     */
    private Date modifytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_d_vote_result.CREATEUSERID
     *
     * @mbggenerated
     */
    private Integer createuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_d_vote_result.MODIFYUSERID
     *
     * @mbggenerated
     */
    private Integer modifyuserid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_d_vote_result.ID
     *
     * @return the value of tb_d_vote_result.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_d_vote_result.ID
     *
     * @param id the value for tb_d_vote_result.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_d_vote_result.VOTEID
     *
     * @return the value of tb_d_vote_result.VOTEID
     *
     * @mbggenerated
     */
    public Integer getVoteid() {
        return voteid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_d_vote_result.VOTEID
     *
     * @param voteid the value for tb_d_vote_result.VOTEID
     *
     * @mbggenerated
     */
    public void setVoteid(Integer voteid) {
        this.voteid = voteid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_d_vote_result.TOPICID
     *
     * @return the value of tb_d_vote_result.TOPICID
     *
     * @mbggenerated
     */
    public Integer getTopicid() {
        return topicid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_d_vote_result.TOPICID
     *
     * @param topicid the value for tb_d_vote_result.TOPICID
     *
     * @mbggenerated
     */
    public void setTopicid(Integer topicid) {
        this.topicid = topicid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_d_vote_result.OPTIONID
     *
     * @return the value of tb_d_vote_result.OPTIONID
     *
     * @mbggenerated
     */
    public Integer getOptionid() {
        return optionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_d_vote_result.OPTIONID
     *
     * @param optionid the value for tb_d_vote_result.OPTIONID
     *
     * @mbggenerated
     */
    public void setOptionid(Integer optionid) {
        this.optionid = optionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_d_vote_result.OPTIONEXTID
     *
     * @return the value of tb_d_vote_result.OPTIONEXTID
     *
     * @mbggenerated
     */
    public Integer getOptionextid() {
        return optionextid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_d_vote_result.OPTIONEXTID
     *
     * @param optionextid the value for tb_d_vote_result.OPTIONEXTID
     *
     * @mbggenerated
     */
    public void setOptionextid(Integer optionextid) {
        this.optionextid = optionextid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_d_vote_result.ALLOWANONYMITY
     *
     * @return the value of tb_d_vote_result.ALLOWANONYMITY
     *
     * @mbggenerated
     */
    public Byte getAllowanonymity() {
        return allowanonymity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_d_vote_result.ALLOWANONYMITY
     *
     * @param allowanonymity the value for tb_d_vote_result.ALLOWANONYMITY
     *
     * @mbggenerated
     */
    public void setAllowanonymity(Byte allowanonymity) {
        this.allowanonymity = allowanonymity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_d_vote_result.VOTEUSERID
     *
     * @return the value of tb_d_vote_result.VOTEUSERID
     *
     * @mbggenerated
     */
    public Integer getVoteuserid() {
        return voteuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_d_vote_result.VOTEUSERID
     *
     * @param voteuserid the value for tb_d_vote_result.VOTEUSERID
     *
     * @mbggenerated
     */
    public void setVoteuserid(Integer voteuserid) {
        this.voteuserid = voteuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_d_vote_result.REMARKS
     *
     * @return the value of tb_d_vote_result.REMARKS
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_d_vote_result.REMARKS
     *
     * @param remarks the value for tb_d_vote_result.REMARKS
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_d_vote_result.DELMARK
     *
     * @return the value of tb_d_vote_result.DELMARK
     *
     * @mbggenerated
     */
    public Byte getDelmark() {
        return delmark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_d_vote_result.DELMARK
     *
     * @param delmark the value for tb_d_vote_result.DELMARK
     *
     * @mbggenerated
     */
    public void setDelmark(Byte delmark) {
        this.delmark = delmark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_d_vote_result.CREATETIME
     *
     * @return the value of tb_d_vote_result.CREATETIME
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_d_vote_result.CREATETIME
     *
     * @param createtime the value for tb_d_vote_result.CREATETIME
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_d_vote_result.MODIFYTIME
     *
     * @return the value of tb_d_vote_result.MODIFYTIME
     *
     * @mbggenerated
     */
    public Date getModifytime() {
        return modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_d_vote_result.MODIFYTIME
     *
     * @param modifytime the value for tb_d_vote_result.MODIFYTIME
     *
     * @mbggenerated
     */
    public void setModifytime(Date modifytime) {
        this.modifytime = modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_d_vote_result.CREATEUSERID
     *
     * @return the value of tb_d_vote_result.CREATEUSERID
     *
     * @mbggenerated
     */
    public Integer getCreateuserid() {
        return createuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_d_vote_result.CREATEUSERID
     *
     * @param createuserid the value for tb_d_vote_result.CREATEUSERID
     *
     * @mbggenerated
     */
    public void setCreateuserid(Integer createuserid) {
        this.createuserid = createuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_d_vote_result.MODIFYUSERID
     *
     * @return the value of tb_d_vote_result.MODIFYUSERID
     *
     * @mbggenerated
     */
    public Integer getModifyuserid() {
        return modifyuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_d_vote_result.MODIFYUSERID
     *
     * @param modifyuserid the value for tb_d_vote_result.MODIFYUSERID
     *
     * @mbggenerated
     */
    public void setModifyuserid(Integer modifyuserid) {
        this.modifyuserid = modifyuserid;
    }
}