package com.unisk.zc.mapper;

import com.unisk.zc.entitys.RegionCode;

public interface RegionCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_D_REGION_CODE
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_D_REGION_CODE
     *
     * @mbggenerated
     */
    int insert(RegionCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_D_REGION_CODE
     *
     * @mbggenerated
     */
    int insertSelective(RegionCode record);
}